<template>
  <div class="space-y-20">
    <section class="container-page pt-16 text-center md:pt-24">
      <h1 class="mx-auto max-w-4xl text-4xl font-semibold tracking-tight text-brand-ink md:text-6xl">
        To revolutionize industries through innovative technology solutions, driving positive change and empowering individuals and businesses
      </h1>
      <p class="mx-auto mt-5 max-w-3xl leading-7 text-slate-500">
        At FutureSphere our mission is to empower individuals and businesses through innovative technology solutions that enrich lives, foster growth, and drive positive change.
      </p>
      <div class="mt-7 flex justify-center gap-3">
        <RouterLink to="/careers" class="btn btn-outline !border-brand-navy !bg-brand-navy !text-white">Signup</RouterLink>
        <RouterLink to="/contact" class="btn btn-primary">Contact Us</RouterLink>
      </div>
      <div class="abstract-tech mt-10 h-80 rounded-3xl"></div>
    </section>

    <section class="container-page grid gap-6 md:grid-cols-2">
      <article class="card fade-in p-7">
        <span class="pill">Our Story</span>
        <p class="mt-5 leading-7 text-slate-500">
          In 2023, our founder, Veda, faced a daunting challenge: organizing the first Global AI Honors summit. Limited in budget but rich in ambition, the team created a platform that connected early-stage innovators with enterprise partners.
        </p>
        <p class="mt-4 leading-7 text-slate-500">
          This success ignited a passion for building practical tools that help organizations move from idea to measurable impact with confidence.
        </p>
      </article>
      <img class="fade-in h-full min-h-80 rounded-3xl object-cover" :src="images.team" alt="FutureSphere team" />
      <img class="fade-in h-full min-h-80 rounded-3xl object-cover" :src="images.team" alt="FutureSphere culture" />
      <article class="card fade-in p-7">
        <p class="leading-7 text-slate-500">
          The success generated by Veda's initiative paved the way for a broader FutureSphere company, with a strong focus on collaboration, intelligent automation, and customer-centered solutions.
        </p>
      </article>
    </section>

    <ClientsStrip />

    <section class="container-page fade-in">
      <SectionHeader tag="Our Values" title="Guided by Integrity and Purpose" />
      <div class="card mt-10 grid gap-4 p-6 md:grid-cols-3">
        <SimpleCard v-for="value in values" :key="value.title" :icon="value.icon" :title="value.title" :description="value.description" />
      </div>
    </section>

    <section class="container-page fade-in text-center">
      <SectionHeader tag="Our Team" title="Meet our team" subtitle="Meet our passionate and talented team, committed to delivering exceptional results." />
      <div class="mt-10 flex flex-wrap items-center justify-center gap-4">
        <img v-for="member in team" :key="member" class="h-24 w-24 rounded-full object-cover ring-4 ring-white md:h-32 md:w-32" :src="member" alt="Team member" />
      </div>
      <div class="mt-6 flex justify-center gap-3 text-brand-accent">
        <button class="grid h-10 w-10 place-items-center rounded-full border">←</button>
        <button class="grid h-10 w-10 place-items-center rounded-full bg-brand-accent text-white">→</button>
      </div>
    </section>

    <OfficesSection />
    <JobsSection />
    <NewsletterCTA />
    <AppFooter />
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue';
import { RouterLink } from 'vue-router';
import AppFooter from '../components/shared/AppFooter.vue';
import ClientsStrip from '../components/shared/ClientsStrip.vue';
import JobsSection from '../components/shared/JobsSection.vue';
import NewsletterCTA from '../components/shared/NewsletterCTA.vue';
import OfficesSection from '../components/shared/OfficesSection.vue';
import SectionHeader from '../components/shared/SectionHeader.vue';
import SimpleCard from '../components/ui/SimpleCard.vue';
import { useReveal } from '../composables/useReveal';
import { images } from '../data/assets';
import { values } from '../data/values';

useReveal();
onMounted(() => {
  document.title = 'FutureSphere | About';
});

const team = [
  'https://placehold.co/180x180/f3d9d9/1A1033?text=VA',
  'https://placehold.co/180x180/eee2cf/1A1033?text=JR',
  'https://placehold.co/180x180/d8d8d8/1A1033?text=MK',
  'https://placehold.co/180x180/d6e5df/1A1033?text=NL',
  'https://placehold.co/180x180/e8d7ff/1A1033?text=SO',
];
</script>
