<template>
  <div class="pt-20">
    <section class="bg-[#F8F7FF] px-6 py-24 text-center lg:py-32">
      <h1 class="mx-auto mb-8 max-w-4xl text-4xl font-bold leading-tight text-gray-900 lg:text-5xl">
        To revolutionize industries through innovative technology solutions, driving positive change and empowering individuals and businesses
      </h1>
      <p class="mx-auto max-w-3xl text-lg leading-relaxed text-gray-500">
        At FutureSphere our mission is to empower individuals and businesses through innovative technology solutions that enrich lives, foster growth, and drive positive change.
      </p>
      <div class="mt-12 flex justify-center gap-3">
        <RouterLink to="/careers" class="inline-flex items-center gap-2 rounded-full border border-[#6B4EFF] px-6 py-3 text-sm font-semibold text-[#6B4EFF] transition-all duration-200 hover:bg-[#6B4EFF] hover:text-white">Signup</RouterLink>
        <RouterLink to="/contact" class="inline-flex items-center gap-2 rounded-full bg-[#6B4EFF] px-6 py-3 text-sm font-semibold text-white transition-all duration-200 hover:bg-[#5538EE]">Contact Us</RouterLink>
      </div>
      <img class="mx-auto mt-12 aspect-[1058/388] w-full max-w-5xl rounded-full object-cover shadow-lg" :src="images.heroTech" alt="FutureSphere technology visualization" />
    </section>

    <section class="mx-auto grid max-w-6xl grid-cols-1 gap-8 px-6 py-16 lg:grid-cols-2 lg:py-24">
      <article class="fade-in rounded-2xl border border-gray-100 bg-white p-8 shadow-sm transition-all duration-300 hover:scale-[1.01] hover:shadow-md">
        <span class="mb-3 block text-sm font-semibold uppercase tracking-widest text-purple-600">Our Story</span>
        <p class="text-base leading-relaxed text-gray-500">
          In 2023, our founder, Veda, faced a daunting challenge: organizing the first Global AI Honors summit. Limited in budget but rich in ambition, the team created a platform that connected early-stage innovators with enterprise partners.
        </p>
        <p class="mt-4 text-base leading-relaxed text-gray-500">
          This success ignited a passion for building practical tools that help organizations move from idea to measurable impact with confidence.
        </p>
      </article>
      <img class="fade-in aspect-[4/3] w-full rounded-3xl object-cover shadow-lg" :src="images.team" alt="FutureSphere team" />
      <img class="fade-in aspect-[4/3] w-full rounded-3xl object-cover shadow-lg" :src="images.team" alt="FutureSphere culture" />
      <article class="fade-in rounded-2xl border border-gray-100 bg-white p-8 shadow-sm transition-all duration-300 hover:scale-[1.01] hover:shadow-md">
        <p class="text-base leading-relaxed text-gray-500">
          The success generated by Veda's initiative paved the way for a broader FutureSphere company, with a strong focus on collaboration, intelligent automation, and customer-centered solutions.
        </p>
      </article>
    </section>

    <ClientsStrip />

    <section class="fade-in mx-auto max-w-6xl px-6 py-16 lg:py-24">
      <SectionHeader tag="Our Values" title="Guided by Integrity and Purpose" />
      <div class="grid grid-cols-2 gap-6 md:grid-cols-3">
        <SimpleCard v-for="value in values" :key="value.title" :icon="value.icon" :title="value.title" :description="value.description" />
      </div>
    </section>

    <section class="fade-in mx-auto max-w-6xl px-6 py-16 text-center lg:py-24">
      <SectionHeader tag="Our Team" title="Meet our team" subtitle="Meet our passionate and talented team, committed to delivering exceptional results." />
      <div class="flex flex-wrap items-center justify-center gap-6">
        <img v-for="member in team" :key="member" class="mb-4 h-24 w-24 rounded-full object-cover ring-4 ring-purple-100" :src="member" alt="Team member" />
      </div>
      <div class="mt-12 flex justify-center gap-3 text-purple-600">
        <button class="grid h-10 w-10 place-items-center rounded-full border border-gray-200 transition-all duration-200 hover:border-purple-500">←</button>
        <button class="grid h-10 w-10 place-items-center rounded-full bg-[#6B4EFF] text-white transition-all duration-200 hover:bg-[#5538EE]">→</button>
      </div>
    </section>

    <OfficesSection />
    <JobsSection />
    <NewsletterCTA />
    <AppFooter />
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue';
import { RouterLink } from 'vue-router';
import AppFooter from '../components/shared/AppFooter.vue';
import ClientsStrip from '../components/shared/ClientsStrip.vue';
import JobsSection from '../components/shared/JobsSection.vue';
import NewsletterCTA from '../components/shared/NewsletterCTA.vue';
import OfficesSection from '../components/shared/OfficesSection.vue';
import SectionHeader from '../components/shared/SectionHeader.vue';
import SimpleCard from '../components/ui/SimpleCard.vue';
import { useReveal } from '../composables/useReveal';
import { images } from '../data/assets';
import { values } from '../data/values';

useReveal();
onMounted(() => {
  document.title = 'FutureSphere | About';
});

const team = [
  'https://placehold.co/180x180/f3d9d9/1A1033?text=VA',
  'https://placehold.co/180x180/eee2cf/1A1033?text=JR',
  'https://placehold.co/180x180/d8d8d8/1A1033?text=MK',
  'https://placehold.co/180x180/d6e5df/1A1033?text=NL',
  'https://placehold.co/180x180/e8d7ff/1A1033?text=SO',
];
</script>
